name: Bug report
description: Create a bug report
labels:
  - 'T: Bug'
  - 'S: Untriaged'
body:
  - type: markdown
    attributes:
      value: |
        Please finish verify steps which list in the end first before create bug report

  - type: textarea
    id: reproduce
    attributes:
      label: Step to reproduce
      description: |
        Please write down the reproduction steps here and include the error log. If necessary, please provide screenshots or recordings.
      placeholder: |
        1.
        2.
        3.
        [Screen recording]
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: |
        Describe what should happened here
      placeholder: |
        It should be ...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behaviour
      description: |
        Describe what actually happened here, screenshots is better
      placeholder: |
        Actually it ...
        [Screenshots]
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Logs
      description: |
        CLI output or browser log.
      placeholder: |
        â¯ pnpm run server

        > bridget@v1.0.0 server /Users/spedon/eden/hugo/bridget
        > run-p vite:server hugo:server
    validations:
      required: false

  - type: textarea
    id: more
    attributes:
      label: Addition details
      description: |
        Describe addition details here
      placeholder: |
        Additional details and attachments
    validations:
      required: false

  - type: input
    id: hugo-version
    attributes:
      label: Hugo version
      description: You can get version output with hugo --version
      placeholder: v0.114.0
    validations:
      required: true

  - type: input
    id: bridget-version
    attributes:
      label: Bridget version
      description: Release version or commit SHA
      placeholder: v1.0.1 or 633f6a40e202a023471c58c09f05a92ec2130c93
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: OS version
      description: OS + version code
      placeholder: Windows 11, macOS 14
    validations:
      required: true

  - type: checkboxes
    id: check
    attributes:
      label: Verify steps
      description: |
        Please ensure you have obtained all needed options
      options:
        - label: Pull request is welcome. Check this if you want to start a pull request
          required: false

        - label: I have searched on [Issue Tracker](https://github.com/Sped0n/bridget/issues), No duplicate or related open issue has been found
          required: true

        - label: Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
          required: true
