name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build (Hugo ${{ matrix.hugo-variant }})
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        hugo-variant: ['Minimum', 'Latest']
    env:
      PUBLISH_ARTIFACTS: ${{ matrix.hugo-variant == 'Latest' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ env.PUBLISH_ARTIFACTS == 'true' && secrets.PAT || github.token }}
          persist-credentials: ${{ env.PUBLISH_ARTIFACTS == 'true' }}

      - name: Setup
        uses: ./.github/actions
        with:
          hugo-variant: ${{ matrix.hugo-variant }}

      - name: Pre-build cleanup
        if: env.PUBLISH_ARTIFACTS == 'true'
        run: rm -rf bundled

      - name: Build
        run: pnpm run build

      - name: Push artifacts
        if: env.PUBLISH_ARTIFACTS == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: 'bundled/**/*.js bundled/**/*.css'
          commit_message: 'ci: update bundled artifacts [skip ci]'
